language: node_js
os: linux
dist: trusty
node_js:
  - '12'

addons:
  sources:
      - google-chrome	    
  packages:	
      - dpkg  
      - google-chrome-stable

cache:
  directories:
    - ./node_modules
    

install:
  - cd frontend && npm install
  
script:
  - npm run test -- --watch=false --no-progress --browsers=ChromeHeadlessNoSandbox
