language: node_js

dist: trusty
sudo: false

language: node_js
node_js:
  - '12'

addons:
  sources:
      - google-chrome	    
  packages:	
      - dpkg  
      - google-chrome-stable

cache:
  directories:
    - ./node_modules

install:
  - cd frontend && npm install

script:
  -  cd frontend && npm run test -- --watch=false --no-progress --browsers=ChromeHeadlessNoSandbox
