language: node_js
os: linux
dist: trusty
node_js:
  - '14'

addons:
  chrome: stable
  sources:
      - google-chrome	    
  packages:	
      - dpkg  
      - google-chrome-stable

cache:
  directories:
    - ./node_modules
    

 
install:
  - cd frontend && npm install
  
script:
  - npm run test
