language: node_js
node_js:
  - "11.0"
branches:
  only:
    - main
before_script:
  - npm install -g @angular/cli
script:
  - npm install
  - npm run build
  - npm run test -- --watch=false --no-progress --browsers=ChromeHeadlessNoSandbox
