language: node_js

dist: trusty
sudo: false

language: node_js
node_js:
  - '12'

addons:
  sources:
      - google-chrome	    
  packages:	
      - dpkg  
      - google-chrome-stable

cache:
  directories:
    - ./node_modules
    
before_install: cd frontend

install:
  - npm install
  
before_script: cd frontend
script:
  -  npm run test -- --watch=false --no-progress --browsers=ChromeHeadlessNoSandbox
